### PR TITLE
Upgraded to Elm 0.18 and bumped version

### PR DESCRIPTION
**Pull request by CallumJHays**

### CODE REVIEW

**Comment by sh4r3m4n** [comment]
Hi @CallumJHays! Thanks for the PR! I'll review this in the next days. I noted that the first commit has a lot of changes because of the elm-format (or similar) tool. The next time please disable it or do a separate commit so I can distinguish the actual changes from the elm-format changes :D

**Comment by sh4r3m4n** [comment]
Merged. Thanks for the PR!!! It's very nice to see the Elm community growing.

**Comment by CallumJHays** [comment]
Ah, sorry man. I completely forgot to get back to this PR. Thanks for accepting it though!
Yeah, loving Elm so far - keen to help it grow!

**Comment by lassik** [comment]
Great project! Please tag the 2.0.2 release so that it's published in the Elm package repository. I just tested the master branch locally with Elm 0.18 and it seems to work fine :)

**Comment by sh4r3m4n** [comment]
Hi @lassik! I forgot to publish this new version, thanks for noting. When I get home I will publish it.

**Comment by sh4r3m4n** [comment]
Done! http://package.elm-lang.org/packages/sh4r3m4n/elm-piano/2.0.2

**Comment by lassik** [comment]
Awesome, thanks :)

**Pull request merged**
